- name: Install and Configure MariaDB
  hosts: TEST 
  become: yes 
  tasks:
    - name: Install MariaDB Server 
      package:
        name: mariadb-server
        state: present 

    - name: Start MariaDB 
      service:
        name: mariadb
        state: started 
        enabled: yes 
        
